### ISSUE TITLE
Right click menu for links and open links in browser in webslice plasmoid

### ISSUE THREAD

**Issue by MurzNN** [Cqoicebordel/webslice-plasmoid#1]
Webslice plasmoid shows webpages good, but functional for opening links in new window is broken. In KDE4 I use Miniweb plasmoid, that open links with _blank target (or via right click menu) in full browser. But in Webslice i see only "Reload" item in right click menu and no way to open link in full browser.
Can you add same functional in your Webslice plasmoid?

**Comment by Cqoicebordel** [comment]
I'll look into that, that's a really great idea !

**Comment by Cqoicebordel** [comment]
It *may* be possible to add this functionnality, but for now, the next version (current head) will have the possibility to open the *current* (not the one hovered) in the default browser.
I'm still investigating on how to do what you are asking for though :)

**Comment by MurzNN** [comment]
Thanks for investigating, I hope you find good way to implement this :) 
As I understand on http://doc.qt.io/qt-5/qml-qtwebkit-webview.html description, webview object must send 2 signals:
- onLinkHovered (when user hover on the link).
- onNavigationRequested (when user click on the link).

**Comment by Cqoicebordel** [comment]
That's what I'm looking at :)

Using middle click is a good idea !

**Comment by Cqoicebordel** [comment]
Ok, I commited something that should work, but doesn't : d488bdf8775f79a6f8b001a520881204f08e1944. I'm trying to ping Qt to know what's going on, but no response so far.

**Comment by MurzNN** [comment]
I create issue in KDE5 about problem with web browser plasmoid functional: https://bugs.kde.org/show_bug.cgi?id=371023 - can you confirm and vote for it too?
I hope that KDE developers will fix something in near future.

**Comment by Cqoicebordel** [comment]
Thanks ! Commented on it :)

**Comment by MurzNN** [comment]
> I'm trying to ping Qt to know what's going on, but no response so far.
Can you post url to your pings? Maybe my additionally pings helps solving problem? :)

**Comment by MurzNN** [comment]
In KDE 5.13 standard web browser widget is rewritten https://bugs.kde.org/show_bug.cgi?id=371023 Can you port your plasmoid to same technology and add this feature? Thanks!

**Comment by Cqoicebordel** [comment]
I did forget to add the link to my previous request to Qt, which ended without any answer : https://forum.qt.io/topic/57541/wrong-mousebutton-returned-in-a-webview-after-onnavigationrequested
I spent some time on it now, because I thought my latest changes brought this as a regression, forgetting it never worked in the first place :/

**Comment by MurzNN** [comment]
Maybe reviewing this commit https://cgit.kde.org/kdeplasma-addons.git/commit/?id=0319b3e9c96f193d6212b9a6d90f29b39cfda594 can help find good way?

**Comment by Cqoicebordel** [comment]
Sadly, no, this changelog doesn't bring anything to the table related to middle click or ctrl+click.

**Comment by MurzNN** [comment]
I test Webslice in KDE 5.13 and right-click menu is same on empty space and on links. But default Web Browser Plasma widget have different right-click menu on links.

**Comment by Cqoicebordel** [comment]
I'm building the context menu myself, and didn't implement anything different in the context menu depending on the context. I'm not even sure I can right now, unless I do a full rewrite, and I don't really want to.
As I said above, the solution right now would be to find a fix for https://forum.qt.io/topic/57541/wrong-mousebutton-returned-in-a-webview-after-onnavigationrequested.

**Comment by Cqoicebordel** [comment]
Finally found a way.
You can now middle click or ctrl+click links to open them in the default browser.
