### ISSUE TITLE
Multiple URLs

### ISSUE THREAD

**Issue by kupiqu** [Cqoicebordel/webslice-plasmoid#10]
Could be possible to have a list of bookmarks? That would help moving between websites.

Ideally they could be those appearing in falkon/konqueror.

**Comment by Cqoicebordel** [comment]
That's kind of a good and bad idea at the same time :)
I see what you want, but I don't think I will implement it in Webslice. For me, Webslice is an easy way to create a widget for you desktop : code a quick web page, and put it in Webslice. It's not supposed to be a web browser, at all. There is another widget providing a (somewhat) full fledged web browser, that could provide access to bookmarks too, I think. If not, there are plasmoid which only purpose is to provide access to bookmarks.

That's why I won't implement this. But thanks for the interest anyway :)

**Comment by kupiqu** [comment]
Fair enough, but believe me, my intention is not to have a full browser on a widget, instead I would like to have an easy way in which a unique widget allows me to efficiently move between very few websites. Right now I'd need to add a widget per website, which is far from ideal.

I just called them bookmarks and refer to full browsers, but I share with you that having a list of hundreds of bookmarks would not be efficient at all.

Perhaps just a specific webslice list (aimed to be very short) that can be set manually or by importing bookmarks from browsers would be the best, but anyways I guess it's not going to happen.

**Comment by Cqoicebordel** [comment]
Bookmarks, in themselves, no.

But indeed, I could add a couple of "alternate URLs", accessible through the context menu, so you could switch between 3 URLs in total.
Would that be of use to you ?

**Comment by kupiqu** [comment]
It certainly would! 

Wondering if there is an easy way to have some flexibility at imposing N? For some users N = 1 is just fine, for me N = 3 would be great, others may need N = 4 or 5.

Perhaps just one field (N = 1) by default with a button to add another field (N++, which can be repeated as needed)?

**Comment by Cqoicebordel** [comment]
True, it would be ideal.

But to be honest, I have _no idea_ how to code that in QML. From what I can see, the settings are dependent on an XML file that describe each setting one by one. I can describe URL1, URL2 and URL3 by hand, but I don't think that I can do it dynamically. In the same way, I can activate in the context menu "Go to URL1"...URL3 by hand (I'm not a 100% sure yet, didn't test it yet), but here too, I don't know how to do it dynamically.
I'm sure it's possible. But the docs are awful, and I'm not sure I want to spend the time on this when the "easy" solution would be good for 95% of users. I'll look around to see if I find an easy way to do it, though.

**Comment by kupiqu** [comment]
That's fair I totally understand and share your point. Why don't you just do it the easy way N=3 and leave this issue open...?

**Comment by Cqoicebordel** [comment]
Because I won't do "bookmarks" ;)

But I changed the name of the topic and reopened it :)

**Comment by Cqoicebordel** [comment]
I did it for N...

QML is a trap. Everything seems really easy, but it's not, and each step to add a feature/fix is incredibly hard and time consuming, and the lack of docs doesn't help. But after tens of hours on this, it works.

I will do a proper release in a couple days.
