### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by null-von-sushi** [Cqoicebordel/webslice-plasmoid#12]
When adding the plasmoid to a dock, and using it as an icon, it would be nice to be able to specify a custom icon for it.

**Comment by Cqoicebordel** [comment]
I agree. Haven't found the way of doing it or the time to do it yet. But it's in my todo list :)

**Comment by Null-Senpai** [comment]
Knowing it's on the to-do list is good enough for me, just wanted to mention it :grinning:

**Comment by KottV** [comment]
+1 vote from me

**Comment by larebsyed** [comment]
Also it would be great if we can show favicon instead of default icon and notification count as well.

**Comment by Cqoicebordel** [comment]
Hi, 
It took me a long, long time, but the feature is now in ! I just released a new version with it in.
You can choose from a file, or use the freedesktop names. The app cuttlefish might help you finding the right icon too :)
