### ISSUE TITLE
Fails in 5.14 with QtWebKit.experimental" is not installed

### ISSUE THREAD

**Issue by MikeMitterer** [Cqoicebordel/webslice-plasmoid#13]
It's really a nice plasmoide but unfortunately it fails with:.

```
Fehler beim Laden der QML-Datei: file:///home/jenkins/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml:25:1: module "QtWebKit.experimental" is not installed
file:///home/jenkins/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml:21:1: module "QtWebKit" is not installed
file:///home/jenkins/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml:25:1: module "QtWebKit.experimental" is not installed
file:///home/jenkins/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml:21:1: module "QtWebKit" is not installed

```

Betriebssystem: KDE neon 5.14
KDE-Plasma-Version: 5.14.1
Qt-Version: 5.11.2
KDE-Frameworks-Version: 5.51.0
Kernel-Version: 4.15.0-36-generic
Art des Betriebssystems: 64-bit
Prozessoren: 4 × Intel® Core™ i5-7400 CPU @ 3.00GHz
Speicher: 7,7 GiB Arbeitsspeicher

**Comment by kupiqu** [comment]
It works here in my up-to-date KDE neon User Edition system as yours.

For the case it's useful, I have the following packages installed (not sure which ones are strictly necessary though):

```
ii  libkf5webkit5:amd64                             5.51.0-0xneon+18.04+bionic+build13               amd64        KDE Integration for QtWebKit.
ii  libqt5webkit5:amd64                             5.212.0~alpha2-15+18.04+bionic+build34           amd64        Web content engine library for Qt
ii  libqt5webkit5-dev:amd64                         5.212.0~alpha2-15+18.04+bionic+build34           amd64        Web content engine library for Qt - development files
ii  qml-module-qtwebkit:amd64                       5.212.0~alpha2-15+18.04+bionic+build34           amd64        Qt WebKit QML module
```

I also have webkitpart installed from https://phabricator.kde.org/source/kwebkitpart/

Hope it helps!

**Comment by MikeMitterer** [comment]
Cool + Thanks for the quick response.
I installed the libs, (not webkitpart) restarted and voila - it works!

**Comment by Cqoicebordel** [comment]
Whoa ! I am amazed of the quickness of the answer, and the solution !
Thanks a mil @kupiqu !!!

And thanks @MikeMitterer for using my plasmoid !!! :)
