### ISSUE TITLE
Stretch plamoid to remaining space in panel

### ISSUE THREAD

**Issue by Programie** [Cqoicebordel/webslice-plasmoid#16]
I want to put a panel on the side of my second monitor showing only a web page in the Web Slice plasmoid. But currently, simply adding the plasmoid to the empty panel ends in the plamoid getting the same height as width. So if the panel has a width of 200 px, the plasmoid also has a width of 200 px but also has a height of 200 px. But I want the plasmoid to use the remaining space (1080 px in my case).

Example using the default URL:
![image](https://user-images.githubusercontent.com/1206521/63794196-be844300-c901-11e9-9393-694d9ced1cba.png)

**Comment by Cqoicebordel** [comment]
It is weird. It's not something I have ever seen.
The capture doesn't show a popup window, it's just the plasmoid directly on the desktop, right ?

**Comment by Programie** [comment]
The screenshot shows the Plasmoid in an empty panel.

I want to use the plasmoid to display some website to have it always in the view on the side of my screen.

**Comment by Cqoicebordel** [comment]
Can you try to restart plasmashell ?

**Comment by Programie** [comment]
Yes, I already did it (I did a full reboot). And it is still displayed in the same size.

**Comment by Cqoicebordel** [comment]
What is your version of Plasma, and the version of the plasmoid you are using ?

**Comment by Programie** [comment]
I'm using Plasma version 5.15.4 and version 1.0.1 of the plasmoid from https://store.kde.org/p/998902

**Comment by Cqoicebordel** [comment]
I'm on 5.16.4, but I didn't touch the code for a while now, so 5.15.4 should work fine. I was on 5.15.4 earlier this year, and didn't have any issue.

I don't suppose you are messing with the JS or any other options.
So, I'm really sorry, but I have no idea why you are seeing this bug. And since I can't reproduce it, I can't fix it.
I'm really sorry.

**Comment by Programie** [comment]
I just tried it with a Live CD of Kubuntu 19.04 and it has the same issue.

Steps to reproduce:

* Start Kubuntu 19.04 (I've tested it in VirtualBox)
* Add empty panel on the side
* Install Webslice Plasmoid using "Get new widgets"
* Add the plasmoid

The result is the same as before:
![image](https://user-images.githubusercontent.com/1206521/63810891-37959180-c926-11e9-978b-602cf95580f5.png)

**Comment by Cqoicebordel** [comment]
I downloaded a VirtualBox machine (skipped the CD altogether, but got that result : 
![screen](https://user-images.githubusercontent.com/2286246/63850913-70b91a80-c995-11e9-8fe0-1df850230d83.gif)
(sorry for the slowness and the quality, my PC is oooold)

No issue here either :/

**Comment by Programie** [comment]
yes, resizing works fine. But I want to add the plasmoid to a panel to have it always docked on the side.

So there is now issue if I add the Webslice plasmoid to the desktop as a standalone widget. The issue only exists if added as a plasmoid to a panel.

**Comment by Cqoicebordel** [comment]
Aaaaah !
That explains a lot ! Sorry if I misunderstood before :)

I _think_ that this is handled by the panel, and not by the plasmoid. From a quick search, I can't find anything. I'll look into it in the coming days, but can't guarantee anything.

**Comment by Cqoicebordel** [comment]
Ok, no, I can probably do something. I don't have the time right now, but I will.
In the mean time, you can try fiddling directly with the plasmoid : 
Try to add `Layout.minimumHeight: 900px` on line 61 of `~/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml`
Beware, this will apply to all Webslices you'll use.

If it works, please tell me :)

**Comment by Programie** [comment]
I just tried to add `Layout.minimumHeight: 900px` to the main.qml but then the plasmoid can't be loaded because of a syntax error. The [documentation](https://doc.qt.io/qt-5/qml-qtquick-layouts-layout.html#minimumWidth-attached-prop) stats, the value should be a real type, so I tried it with "900" instead of "900px". Now the plasmoid loads but the property doesn't have any effect on the plasmoid height.

**Comment by Cqoicebordel** [comment]
Thanks for testing and for finding the correct value. I hoped it would be a quick fix.

I'll have to dig then. And again, it will take a bit of time :/

**Comment by Cqoicebordel** [comment]
Hi,  
I just released a new version, with an experimental implementation of this feature, to fill space.

If and when you'll test it, I'm eager for some feedback :)

**Comment by Programie** [comment]
Hi, sorry for the late feedback.

I just tested the new version and it's working as expected after setting the option "Fill the whole width and height" in the experimental settings.

**Comment by Cqoicebordel** [comment]
Thanks for the feedback !!!
