### ISSUE TITLE
Add zoom setting

### ISSUE THREAD

**Issue by efibe** [Cqoicebordel/webslice-plasmoid#17]
It would be great if the webpages could be zoomed out to look tiny. That could fit more stuff into the desktop.

**Comment by Cqoicebordel** [comment]
That's a good idea !
I have no idea if and when I would have enough time to be able to implement that though. 

In the meantime, you can use
`document.body.style.zoom = 1.0`
in the custom javascript to change the zoom factor of the page (1.0 being 100%)

**Comment by Cqoicebordel** [comment]
Hi,
I just released a new version, with this feature in. Enjoy :)
