### ISSUE TITLE
Adding webslice anywhere crashes plasmashell until its removed from .config/plasma-org.kde.plasma.desktop-appletsrc

### ISSUE THREAD

**Issue by ikidd** [Cqoicebordel/webslice-plasmoid#18]
Plasma 5.18.5, not sure if it's related to that version of plasma or some QT controls that were updated at the same time.  I downgraded systemd and plasmashell and that didn't seem to help so I suspect the QT update but haven't confirmed.

**Comment by Cqoicebordel** [comment]
I got the same report on https://www.pling.com/p/998902/.
Sadly, not being on it myself (and having so little time available), a fix will not come in the very short term. I hope that a fix will come eventually though :/

**Comment by beermad** [comment]
Same problem on my system. A pity because this is an incredibly useful widget.

For reference, it throws an error in the syslog:
`QThread[1892]: segfault at 8 ip 00007fcaa9234b2e sp 00007fca157fb7d0 error 4 in libQt5Core.so.5.15.0[7fcaa909a000+306000]`

**Comment by Cqoicebordel** [comment]
Thanks for the info !
I also saw your post on the manjaro forum.
If you find a solution or just help, I'll update the plasmoid as soon as possible. I can't dev it blind :/

**Comment by Cqoicebordel** [comment]
Ok, I may have a fix. If you are willing to test, here is the steps (if you are not willing, please tell me too).
The only file to be changed is `/home/cqoicebordel/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/mail.qml`
1/ l21, change `import QtWebKit 3.0` to `import QtWebView 1.1`
2/ Comment all "experimental" lines (l25, l84, l85, l120, l121 and l124)
3/ Comment the `onNavigationRequested` function (l135, l136, l137, l138, l139, and l140)
4/ Make sure the package `qml-module-qtwebview` is installed
And now, you can test it.

If it works, you'll have a couple less features (notably JS injection, and middle click), but I'll be able to fix the first one, at least, in a proper release.

**Comment by beermad** [comment]
> Ok, I may have a fix. If you are willing to test, here is the steps (if you are not willing, please tell me too).
> The only file to be changed is `~/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml`
> 1/ l21, change `import QtWebKit 3.0` to `import QtWebView 1.1`
> 2/ Comment all "experimental" lines (l25, l84, l85, l120, l121 and l124)
> 3/ Comment the `onNavigationRequested` function (l135, l136, l137, l138, l139, and l140)
> 4/ Make sure the package `qml-module-qtwebview` is installed
> And now, you can test it.
> 
> If it works, you'll have a couple less features (notably JS injection, and middle click), but I'll be able to fix the first one, at least, in a proper release.

Thanks. I'll give it a try later today and report back.

**Comment by beermad** [comment]
Hi,
Tested and found to work. Many thanks.
A couple of observations:

- File to edit is actually main.qml, not mail.qml
- Don't make the mistake I made of trying to comment lines out with a hash: it needs "//".
- Watch out for line 62, where the statement flows over two lines, so both need to be commented-out.
- On Manjaro, the package that needs to be installed is qt5-webview
Good to have this useful utility back. Thanks.

**Comment by Cqoicebordel** [comment]
Thanks for the feedback !
It looks like it breaks more features than I hoped (on my tests, the context menu doesn't work anymore). So I'm trying things but it's a PITA.

In any case, I'll try to publish a version specific for Plasma 5.19+

**Comment by beermad** [comment]
> Thanks for the feedback !
> It looks like it breaks more features than I hoped (on my tests, the context menu doesn't work anymore). So I'm trying things but it's a PITA.

I get a context menu with three items: "save image", "copy image" and "copy image address". The first one doesn't do anything but the other two work correctly.

**Comment by Cqoicebordel** [comment]
Yeah, but before, I had a beautiful context menu, with customized items. Back, refresh, configure. Now, it's the webview automatic context menu. It could work for most usage, but it's not how I wanted it.

Looks like I'll have to rebuild the plasmoid from the ground up, using WebEngineView, instead of WebEngine. That will take _a lot_ of time. So for now, I'll just publish the limited version to fix the current issue, and we'll see about a full version.

**Comment by ikidd** [comment]
Works for me after installing arch package qt5-webview.

TYVM, I appreciate you working around that and appreciate the widget.

**Comment by Cqoicebordel** [comment]
Cool !  
Yeah, closing. I don't need a bug to remember I have to rebuild the whole thing ;)
