### ISSUE TITLE
Disable touch functional for web browser and enable classic interface behavior

### ISSUE THREAD

**Issue by MurzNN** [Cqoicebordel/webslice-plasmoid#2]
Will be good to have option for disable touch functional (zoom on double click, drag on any click+move without any way to select text, etc) and enable classic desktop web browser behavior in webslice plasmoid.

**Comment by Cqoicebordel** [comment]
Indeed that would be good. I'll look into that, but I'm afraid there isn't a lot I can do : the webview is kind of a black box.

**Comment by MurzNN** [comment]
Seems that webview class support disabling drag:
http://api.kde.org/4.x-api/kdelibs-apidocs/plasma/html/classPlasma_1_1WebView.html#ae7e516fc158df73f873a12366399cabd
```
void Plasma::WebView::setDragToScroll (bool drag) 	
Sets if the page can be scrolled around by dragging the contents with the mouse. 
```
And right click event:
```
void Plasma::WebView::contextMenuEvent (QGraphicsSceneContextMenuEvent * event)
```

**Comment by Cqoicebordel** [comment]
Thanks for the link.
Unfortunately, the new plasmoid must use QML, and so, I have to use this object instead, which is a bit more... limited : http://doc.qt.io/qt-5/qml-qtwebkit-webview.html
Even just for having a context menu I had to use a trick that wasn't obvious nor easy.

As of today, a lot of functionnality of the plasmoid come from non documented and non stable APIs http://rschroll.github.io/beru/2013/08/21/qtwebview.experimental.html

QML 5/KF5 is a real mess, without a lot of possibility. But there is always a way :)

**Comment by MurzNN** [comment]
Seems that we can disable touch functional via setting:
http://doc.qt.io/qt-4.8/qml-webview.html#pressGrabTime-prop
- here http://doc.qt.io/qt-4.8/qml-webview.html is description:

> The pressGrabTime property defines the time the user must touch or press a mouse button over the WebView before the Web content will receive the move events it needs to select text and images.

Can you try this option in your webslice plasmoid?

**Comment by MurzNN** [comment]
Is there any improvements about this problem in new Qt versions?

**Comment by MurzNN** [comment]
Seems that in KDE 5.13 standard widget https://bugs.kde.org/show_bug.cgi?id=371023 this problem is solved, can you port your plasmoid to same technology?

**Comment by MurzNN** [comment]
I test widget in KDE 5.13 Beta and it works better, without touch functional, so let's close this issue.
