### ISSUE TITLE
Opening configuration causes webview to disappear 

### ISSUE THREAD

**Issue by pipipear** [Cqoicebordel/webslice-plasmoid#33]
Regardless of whether the plasmoid is placed on a panel or the desktop, opening the configuration/editing a panel causes the webview to disappear. After the configuration/panel edit is closed, the webview remains hidden until the plasmoid is moved to the desktop or a different panel. This happens regardless of what the _"Plasmoid background color"_ is set to.

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.22.90
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.11.19-051119-generic (64-bit)
Graphics Platform: X11
Graphics Processor: Mesa Intel® Iris® Plus Graphics

**Comment by Cqoicebordel** [comment]
Thanks for this detailed report, I appreciate particularly the nice touch of the plasmoid background color.

Sadly, for technical reasons, I'm stuck to Kubuntu 20.04 right now, so I can't test anything beyond it. I hope I'll be able to go to 22.04, but I'm not sure how yet.  

So, I'm really sorry, I can't do anything right now about it.  
But be sure that I soon as I can, I'll try to reproduce and fix that bug.

**Comment by pipipear** [comment]
I really appreciate your work on this project. Just for reference, here is the console output from plasmashell when I open the configuration.
```
Opening menu at 58 0
QQmlEngine::setContextForObject(): Object already has a QQmlContext
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86 ): This returns 1 when using Qt HiDPI scaling.
kf.kirigami: Previous message repeats 7 times.
QQmlEngine::setContextForObject(): Object already has a QQmlContext
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:184:17: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:184:17: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:184:17: QML SpinBox: Binding loop detected for property "implicitHeight"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:168:17: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:168:17: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:168:17: QML SpinBox: Binding loop detected for property "implicitHeight"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:108:13: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:108:13: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:108:13: QML SpinBox: Binding loop detected for property "implicitHeight"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:184:17: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:168:17: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/ConfigGeneral.qml:108:13: QML SpinBox: Binding loop detected for property "implicitWidth"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:38:5: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:38:5: QML Loader: Binding loop detected for property "height"
file:///home/n/.local/share/plasma/plasmoids/org.kde.plasma.mediacontroller_plus/contents/ui/CompactRepresentation.qml:108:9: Unable to assign [undefined] to int
file:///home/n/.local/share/plasma/plasmoids/org.kde.plasma.volumewin7mixer/contents/ui/Mpris2DataSource.qml:28:2: Unable to assign [undefined] to QString
file:///home/n/.local/share/plasma/plasmoids/org.kde.plasma.volumewin7mixer/contents/ui/Mpris2DataSource.qml:27:2: Unable to assign [undefined] to bool
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
file:///home/n/.local/share/plasma/plasmoids/org.kde.plasma.mediacontroller_plus/contents/ui/TrackInfo.qml:34:5: Unable to assign [undefined] to int
file:///home/n/.local/share/plasma/plasmoids/org.kde.plasma.mediacontroller_plus/contents/ui/CompactRepresentation.qml:108:9: Unable to assign [undefined] to int
file:///home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml:162:13: Unable to assign [undefined] to bool
Error: cannot change the containment to AppletsLayout
Error: cannot change the containment to AppletsLayout
js: WS Closed:  [object CloseEvent]
```

**Comment by Cqoicebordel** [comment]
Sorry, I didn't see your answer until now.

In the log, the "loop detected" is usually nothing.  
So there is only one error left. Which point to the "display site behavior" setting, or the fact that the plasmoid is "open" (the site is visible) or not.  

So, if you are willing, the first test would be to change the "display site" setting, and restart plasmashell. Try to reopen the settings to see if the bug is still there, change the setting back, and restart plasmashell, and try to see if the bug is still there again.  
I doubt it's the solution, but we never know.

And next, something to test too, if you are still willing :  
Open `/home/n/.local/share/plasma/plasmoids/cqcb.plasma.webslice/contents/ui/main.qml`. 
Edit `import QtQuick 2.12`, `import QtQuick.Controls 2.12` and `import QtQml 2.12`to remove the `2.12` part at the end of those line. Save, restart plasmashell, and retest the bug. If there is an error message instead of the plasmoid, try putting 2.15 instead of 2.12.

Yeah, both of those try are shots in the dark. I have no idea what the cause of the bug is, sorry :/

**Comment by pipipear** [comment]
Thanks for these suggestions, I toggled the _display site behaviour_ setting back and forth and the issue resolved itself.

**Comment by Cqoicebordel** [comment]
Ah cool ! I'm glad !  
And thanks for telling me :)
