### ISSUE TITLE
[Feature request] Convert to icon when webslice plasmoid placed on panel

### ISSUE THREAD

**Issue by MurzNN** [Cqoicebordel/webslice-plasmoid#7]
When I place webslice plasmoid on panel - it stay as small window with web page. But "Web browser" plasmod converts to clickable icon, that shows popup window with web page. Will be good to see same behavior in webslice plasmoid too - optionally (or automatic by widget size) convert to clickable icon.

**Comment by Cqoicebordel** [comment]
Isn't that the case already ? There is the option "Display a button that open the site in a new panel" in the settings, if I'm not mistaken.
Unless I didn't understand your request.

**Comment by MurzNN** [comment]
If I add webslice to panel, it looks like here: http://i.imgur.com/06buCPX.png
And I can't find option "Display a button that open the site in a new panel": http://i.imgur.com/e2pRrWP.png 
http://i.imgur.com/fszO5GS.png

**Comment by MurzNN** [comment]
Here is screenshot from KDE 5.13 (from KDE Neon developer iso) where is standard Web Browser plasmoid & Web Slice are added to panel: https://i.imgur.com/WPyHCuf.png
So standard Web Browser converted to icon, but Web Slice - not. Can you reproduce this on your side and try to fix?

**Comment by kupiqu** [comment]
Mmm, I've always used it as an icon

**Comment by MurzNN** [comment]
Yes, manual setting works well, thanks! I forgot about it. But next problem is that popup window have too small size: https://i.imgur.com/SJj5o6i.png
Even if I setup min-width=800px in widget settings. Can you review this problem?

**Comment by MurzNN** [comment]
Also will be good to setup the icon, that shows in panel button.

**Comment by Cqoicebordel** [comment]
For the size of the popup, there is another issue filed here about it. I spent some time on it yesterday, and didn't find a solution.
For the icon, it might be possible, but I'll have to look for it too.

**Comment by kupiqu** [comment]
'alt + right click' can help resizing but size restores to default settings after plasma restarts :/

**Comment by MurzNN** [comment]
About resize there are another issue: https://github.com/Cqoicebordel/webslice-plasmoid/issues/9
This is about convert to icon: feature exits in settings and works, so let's close.

**Comment by KottV** [comment]
though its closed
+1 for custom icon!
