### ISSUE TITLE
Let user define dimensions of popup

### ISSUE THREAD

**Issue by Cris70** [Cqoicebordel/webslice-plasmoid#9]
When used in a panel and in "button mode", there's no way to define the size of the popup window you get when clicking on the button.
There show be a setting in the configuration dialog to let users define it.
(Also could you clarify on the "minimum content width" option meaning?)

**Comment by Petross404** [comment]
I was about to post the same feature request.

**Comment by Cris70** [comment]
Hi @Cqoicebordel , may I know why did you close this issue without a comment?
Is it solved in a new release? How?
Thank you in advance

**Comment by Cqoicebordel** [comment]
The comment was in the commit 2ba713b, which said "Added the possibility to change the popup's size, when the plasmoid is in the button format. Fix #9" :)

For now, it's just the code in the repo. In a couple of days (maybe today), I will do a proper release, with a .plasmoid file.

**Comment by Cris70** [comment]
Thank you!!

**Comment by Petross404** [comment]
Nice :+1:
